name: 'pr_workflow'
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - feature/*
  workflow_dispatch:

jobs:
  test_format:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: create container
        run: |
          docker compose up docker-compose-train.yaml --build
      
        

