name: 'pr_workflow'
on:
  pull_request:
    branches:
      - master

jobs:
  test_format:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: create container
        run: |
          docker build -t test_app:latest .
          docker run test_app:latest
      
        

